### ISSUE TITLE
Updates to works page

### ISSUE THREAD

**Issue by apinkney0696** [sciencehistory/scihist_digicoll#1777]
A collection of potential additions and changes related to the works page interface/features:

- [ ] Add "Read More" Works Description Expander , Ticket #1774
- [ ] Section Expandables/Rename Section Titles on Works Page, Ticket #1775 
- [ ] Enhance "related items" feature, Ticket, #1317
- [ ] New "Learn More..." Section on works page, Ticket #1776

See below for an illustration and descriptions of my suggested changes/additions. Everything is totally flexible - we can discuss the individual projects on the specific ticket pages!

![opendocument](https://user-images.githubusercontent.com/78036563/178281006-5864205e-2866-442e-a30c-5a9114ab5aa3.jpg)

**Comment by apinkney0696** [comment]
Going to close this, as we've finalized all parts we were interested in completing at this time.
