### ISSUE TITLE
Launch day checklist

### ISSUE THREAD

**Issue by eddierubeiz** [sciencehistory/scihist_digicoll#407]
A list of steps to describe the technical aspects of launch. This is a draft for now.

* `chf_sufia` -- our old app
* `scihist_digicoll` -- our new app

(In "Review" zenhub pipeline to make sure we review it -- then it will go back to 'ready' waiting for launch day). 

## Tuesday Oct 29 (7 days before go live)

- [x] Do an export/import (including derivatives and DZI creation)
- [x] Run import audit
- [x] Run check against fedora
- [x] Run orphan files check
- [x] Run fixity check on ALL files in repo (CYCLE_LENGTH=0) (should take around 14 hours). 

* Intentionally being done 7 days in advance, so if anything unexpected happens, or is found in reports, we have time to investigate, respond, and decide if it should mean postponing launch or we're still good. 

## Wed Oct 30 -- Friday Nov 1
- [x] Switch  `scihist_digicoll` to the "new" staging domain name and make sure there are no configuration errors.
  - [x] Check that `app_url_base` key in `local_env.yml` is correct
- [x] Move over staging Elastic IP, shut down `chf_sufia` staging.
- [x] Delete chf_sufia **staging** VMs, disks, S3 buckets. 
- [x] Have digitization staff look over the new application for any unexpected issues.
* Doing these steps less than 7 days out since errors should be smaller if they come up and to minimize the time we don't have staging if a `chf_sufia` bug crops up before the new launch.

* scihist_digicoll should match chf_sufia at this point. Is there anything we want to do in this last week to check to make sure it really does match?

* Hopefully we have been doing this _before_ this point, we don't need to wait, we have the remainder of October. Should we think about what things need to be done to "QA" that, and who should do them when?

## Monday Nov 4th:  1 day before go-live
starting at 9am .
- [x] Final go-ahead for go-live from Hillary/~Ron~/Chuck -- did we find anything unexpected in previous week? If so, have we resolved it such that we are still comfortable going live, knowing that it will not be easy to reverse course?
- [x] 9:15am(-9:30am) Lock admin users out of chf_sufia (`logins_disabled` in local_env.yml, or change source code to default `logins_disabled` to true)
- [x] 9:30 export from chf_sufia. (~3 hours. So until 12:30). 
- [x] 12:30pm do the import, derivatives generation, DZI generation. (~30 minutes)
- [x] 12:30pm run the audit (~2 minutes)
- [x] 12:30pm Run check-against-fedora (~3 hours, done around 3:30pm). 
- [x] Fixity check on any newly imported things needing fixity checks (not enough time for everything at this point, we rely on past fixity checks). 
- [x] Rename ssh keys so the new web server will get the current ones avoiding the need for developers to worry about server switches. 
- [x] Assign a domain name to the elastic IP for Sufia, to access old app for any testing.

## Tuesday Nov 5th: GO LIVE DATE
Go live, 9am. 
- [x] Ansible change to scihist_digicoll production servers can respond to `digital.sciencehistory.org` 
- [x] Switch IP addresses to `digital.sciencehistory.org` points to new thing
  - [x]  Verify  that `app_url_base` key in `local_env.yml` is correct
- [x] Use Ansible to assign new domain name to Sufia server on local_env file
  - [x] Move new Elastic IP to the old Sufia server.
  - [x] Leave Fedora running for export of RDF data (See #393)
    - [x] Export RDF on Sufia Fedora (This can be pushed to the following day if problems in earlier steps arise)
      - [x] Run export using Fedora disk (/opt/fedora-data) for data storage
      - [x] Archive and compress fedora RDF export
      - [x] Back up RDF export to S3 backup bucket

* Staff is still locked out from logging into chf_sufia *and* scihist_digicoll, metadata/ingest work is halted. 
* chf_sufia is _not_ accessible anymore to compare, is this okay?  

## Wed Nov 6th

- [x] Re-enable staff access to new app -- first check with Hillary/Chuck and make sure all is well

We will reenable editing on new thing. *Before* we do this, we could still easily switch back to `chf_sufia`. Or re-sync any data from chf_sufia. 

*After* this happens, it will be much harder to go back or recover missing data, as changes will have been made in scihist_digicoll, and it will no longer be expected to match chf_sufia. 

What additional checks/QA, if any, should we be doing to be confident in pressing this button? What is the right day to press the button?

## ~1~ 2 week out
- [x] Delete chf_sufia bucket contents
- [x] Delete chf_sufia solr, jobs, and web VMs.

### project cleanup
- [x] "archive" the github chf_sufia project
- [x] rename the Honeybadger projects, no longer "experimental", but old one is "archived". 

## 1 month out
- [x] Delete chf_sufia fedora VM. 
- [x] Delete chf_sufia Fedora binary backups and postgres database but _not_ RDF export. 

* (Extra cost borne until we do these things, but *really* no going back after this. When should they be done? A week later? Two? Four?)

**Comment by eddierubeiz** [comment]
This purposely leaves out any and all communications pertaining to the launch.

**Comment by sanfordd** [comment]
All of the data has been removed. The tape backups contain a last resort cold copy of the data if we ever need to access the original fedora files. Otherwise @eddierubeiz's export of metadata and other information will be retained if we need it.
