### ISSUE TITLE
Public view needs non-public items for logged in users

### ISSUE THREAD

**Issue by jrochkind** [sciencehistory/scihist_digicoll#432]
We were trying to avoid this, but it's just inconvenient for various things staff wants to do, and also really a necessary pre-requisite for #171 batch edit needs -- really need to be able to select items for batch editing using the full facetting power of the public UI. 

So. 

- [x] For logged in users only, non-public items should show up in front-end search. They should still not show up for non-logged in users. 
- [x] non public items should be clearly identified as "private" in UI, when they do show up
- [x] logged-in users need a facet/limit for public/non-public #457
- [x] _child items_ that are private need to be shown _only_ for logged-in users (see #449 )...
- [x] ... but also labeled as private (see #489)
- [x] All items need an "Edit" button next to them for staff users (this was intended to be so, but keeps not working, we need to add a test and make it work).

**Comment by eddierubeiz** [comment]
All of the above are ready in production. See e.g. 
https://digital.sciencehistory.org/works/vcs937d
